# Generated by Django 5.1.4 on 2025-03-10 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoPregunta', models.CharField(max_length=200)),
                ('fechaPubli', models.DateTimeField(verbose_name='Fecha publicada')),
            ],
        ),
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoEleccion', models.CharField(max_length=200)),
                ('voto', models.IntegerField(default=0)),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.pregunta')),
            ],
        ),
    ]
